name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1"
      
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4
      
      - name: Create cache directories
        run: mkdir -p ~/.luarocks
      
      - name: Cache LuaRocks dependencies
        uses: actions/cache@v3
        with:
          path: ~/.luarocks
          key: ${{ runner.os }}-luarocks-${{ hashFiles('**/*.rockspec') }}
          restore-keys: |
            ${{ runner.os }}-luarocks-
      
      - name: Install luacheck
        run: luarocks install luacheck
      
      - name: Check formatting with stylua
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua/
        
      - name: Run Luacheck
        run: luacheck lua/
  
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        neovim-version: [v0.8.0, v0.9.0, stable, nightly]
    
    name: Test with Neovim ${{ matrix.neovim-version }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim-version }}
      
      - name: Install Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1"
      
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4
      
      - name: Create cache directories
        run: |
          mkdir -p ~/.luarocks
          mkdir -p ~/.local/share/nvim/site/pack
      
      - name: Cache LuaRocks dependencies
        uses: actions/cache@v3
        with:
          path: ~/.luarocks
          key: ${{ runner.os }}-luarocks-${{ hashFiles('**/*.rockspec') }}-${{ matrix.neovim-version }}
          restore-keys: |
            ${{ runner.os }}-luarocks-
      
      - name: Cache plugin dependencies
        uses: actions/cache@v3
        with:
          path: ~/.local/share/nvim/site/pack
          key: ${{ runner.os }}-nvim-plugins-${{ hashFiles('**/Makefile') }}-${{ matrix.neovim-version }}
          restore-keys: |
            ${{ runner.os }}-nvim-plugins-
      
      - name: Install test dependencies
        run: |
          # Install LuaFileSystem first as it's required by Busted
          luarocks install luafilesystem
          # Install test framework and assertions
          luarocks install busted
          luarocks install luassert
          luarocks install penlight
          # Install in local directory to ensure visibility
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          if [ ! -d "$HOME/.local/share/nvim/site/pack/vendor/start/plenary.nvim" ]; then
            echo "Cloning plenary.nvim..."
            git clone --depth=1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          else
            echo "plenary.nvim directory already exists, updating..."
            cd ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim && git pull origin master
          fi
      
      - name: Set up test environment
        run: |
          mkdir -p ~/.local/share/luarocks
          ln -sf $(luarocks path --lr-bin) ~/.local/share/luarocks/bin
          echo "$HOME/.local/share/luarocks/bin" >> $GITHUB_PATH
          echo "LUA_PATH='$(luarocks path --lr-path);./?.lua;./?/init.lua'" >> $GITHUB_ENV
          echo "LUA_CPATH='$(luarocks path --lr-cpath)'" >> $GITHUB_ENV
          busted --version
      
      - name: Display Neovim version
        run: nvim --version
      
      - name: Run tests
        run: |
          make test-debug
  
  documentation:
    needs: [lint, test]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1"
      
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4
      
      - name: Create cache directories
        run: mkdir -p ~/.luarocks
      
      - name: Cache LuaRocks dependencies
        uses: actions/cache@v3
        with:
          path: ~/.luarocks
          key: ${{ runner.os }}-luarocks-docs-${{ hashFiles('**/*.rockspec') }}
          restore-keys: |
            ${{ runner.os }}-luarocks-docs-
      
      - name: Install dependencies for ldoc
        run: |
          # Install dependencies required by ldoc
          sudo apt-get update
          sudo apt-get install -y lua-discount
          
      - name: Install ldoc
        run: luarocks install ldoc
      
      - name: Verify ldoc installation
        run: |
          which ldoc || echo "ldoc not found in PATH"
          ldoc --version || echo "ldoc command failed"
          
      - name: Generate API documentation
        run: |
          mkdir -p doc/luadoc
          ldoc lua/ -d doc/luadoc -c .ldoc.cfg || echo "ldoc generation failed, but continuing"
          
      - name: List generated documentation
        run: ls -la doc/luadoc || echo "No documentation generated"
        
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli@0.37.0
      
      - name: Run markdownlint
        run: markdownlint '**/*.md' --config .markdownlint.json || true
        
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress '**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check Lua code blocks in markdown
        run: |
          find . -type f -name "*.md" -exec grep -l '```lua' {} \; | while read -r file; do
            echo "Checking Lua snippets in $file"
            
            # Create a temporary directory for the snippets
            TEMP_DIR=$(mktemp -d)
            
            # Extract Lua code blocks
            grep -n '^```lua$' "$file" | while read -r line_start; do
              # Get the line number where the lua block starts
              line_num=$(echo "$line_start" | cut -d: -f1)
              
              # Find the line number where the next ``` appears
              line_end=$(tail -n +$((line_num+1)) "$file" | grep -n '^```$' | head -1 | cut -d: -f1)
              if [ -n "$line_end" ]; then
                line_end=$((line_num + line_end))
                
                # Extract the lua snippet
                snippet_file="${TEMP_DIR}/snippet_${line_num}.lua"
                sed -n "$((line_num+1)),$((line_end-1))p" "$file" > "$snippet_file"
                
                # Check syntax if file is not empty
                if [ -s "$snippet_file" ]; then
                  echo "  Checking snippet starting at line $line_num in $file"
                  luac -p "$snippet_file" || echo "Syntax error in $file at line $line_num"
                fi
              fi
            done
            
            # Clean up
            rm -rf "$TEMP_DIR"
          done